# Generated by Django 5.0 on 2024-02-09 23:01

import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pong.models.get_upload_to),
        ),
    ]
