# Generated by Django 5.0 on 2023-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
