# Generated by Django 5.0 on 2024-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_42student',
            field=models.BooleanField(default=False),
        ),
    ]
