# Generated by Django 5.0 on 2023-12-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
