# Generated by Django 5.0 on 2024-02-08 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_socials_remove_userprofile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='socials',
        ),
        migrations.AddField(
            model_name='socials',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
