# Generated by Django 5.0 on 2024-02-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_remove_userprofile_socials_socials_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
