# Generated by Django 4.2.3 on 2024-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_storeitem_useritem_remove_userprofile_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='whatis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
