# Generated by Django 5.0 on 2024-01-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_userprofile_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
