# Generated by Django 5.0 on 2023-12-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_remove_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
