# Generated by Django 5.0 on 2024-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_storeitem_whatis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='whatis',
        ),
        migrations.AddField(
            model_name='useritem',
            name='whatis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
