# Generated by Django 5.0 on 2024-02-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_remove_storeitem_whatis_useritem_whatis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pong.social'),
        ),
    ]
