# Generated by Django 5.0 on 2024-02-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_alter_userprofile_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='store_items',
            field=models.ManyToManyField(blank=True, through='pong.UserItem', to='pong.storeitem'),
        ),
    ]
