# Generated by Django 4.2.3 on 2024-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_userprofile_store_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='category_name',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
