# Generated by Django 5.0 on 2024-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_storeitem_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='elo_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
