# Generated by Django 5.0.1 on 2024-01-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_alter_message_room_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvitation',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='gameinvitation',
            name='inviting_user',
        ),
        migrations.RemoveField(
            model_name='gamewarning',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='gamewarning',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jwttoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='GameInvitation',
        ),
        migrations.DeleteModel(
            name='GameWarning',
        ),
        migrations.DeleteModel(
            name='JWTToken',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
