# Generated by Django 5.0 on 2024-01-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_alter_message_room_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvitation',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='gameinvitation',
            name='inviting_user',
        ),
        migrations.RemoveField(
            model_name='gamewarning',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='gamewarning',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jwttoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='not saved', max_length=100),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='GameInvitation',
        ),
        migrations.DeleteModel(
            name='GameWarning',
        ),
        migrations.DeleteModel(
            name='JWTToken',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
