# Generated by Django 5.0 on 2024-01-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='qcl134moIA7MJt7dIQYD8GI4Ck8uzk3US19iIhrRlnZW2nCpqAZhbaKEAXhJaPrX', max_length=255),
        ),
    ]
