# Generated by Django 4.2.3 on 2024-02-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_remove_gameinvitation_invited_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='participants',
            new_name='standings',
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pong.tournament'),
        ),
        migrations.DeleteModel(
            name='MatchRecord',
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
    ]
