# Generated by Django 5.0 on 2024-02-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_userprofile_elo_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='is_status',
            new_name='show_status',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pong_wallet',
            new_name='indian_wallet',
        ),
    ]
