# Generated by Django 5.0 on 2024-01-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='Um5wPuthISIt740g9mjvlSDO4jkzWucTn9LqtoboY5L4S62pcGxfgvH1ffkSOleZ', max_length=255),
        ),
    ]
