# Generated by Django 4.2.3 on 2024-02-13 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_remove_storeitem_is_bought_useritem_is_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='elo_point',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='indian_wallet',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
