# Generated by Django 5.0 on 2024-01-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
