# Generated by Django 5.0 on 2024-01-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_alter_token_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='VerifyToken',
        ),
    ]
