# Generated by Django 5.0 on 2024-01-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0014_rename_token_verifytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifytoken',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
