# Generated by Django 4.2.3 on 2024-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0014_tournamentmatch_loserscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='loserscore',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winnerscore',
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='loserscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='winnerscore',
            field=models.IntegerField(default=0),
        ),
    ]
