# Generated by Django 4.2.3 on 2024-02-13 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0015_remove_tournamentmatch_loserscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_lost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MatchRecord',
        ),
    ]
