# Generated by Django 4.2.3 on 2024-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0016_game_loser_delete_matchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
