# Generated by Django 4.2.3 on 2024-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0017_game_finished_at_game_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_at',
        ),
        migrations.AddField(
            model_name='game',
            name='game_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
