version: "3.9"

services:
  indianpong:
    image: aktas/indianpong:latest
    build:
      context: ./indianpong
    container_name: indianpong
    volumes:
      - ./staticfiles:/ft_transcendence/staticfiles
      - ./media:/ft_transcendence/media
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - indianpongnet
  db:
    container_name: db
    image: db
    build:
      context: ./
      dockerfile: docker.dockerfile
    restart: always
    networks:
      - indianpongnet
  
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - indianpong
    networks:
      - indianpongnet
    volumes:
      - ./staticfiles:/ft_transcendence/staticfiles
      - ./media:/ft_transcendence/media
    
networks:
  indianpongnet:
    driver: bridge

