version: "3.9"

services:
  indianpong:
    image: aktas/indianpong:latest
    build:
      context: ./indianpong
    container_name: indianpong
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
       - indianpongnet

  db:
    container_name: db
    image: db
    build:
      context: ./
      dockerfile: docker.dockerfile
    restart: always
    networks:
      - indianpongnet
    
networks:
  indianpongnet:
    driver: bridge
