FROM nginx:alpine

# Update package list and install openssl
RUN apk update && apk add openssl

# Create a directory for the certificates
# Generate a self-signed certificate
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -days 365 -nodes -subj '/CN=localhost'

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the Nginx port
EXPOSE 8000
EXPOSE 8443